version: 2
jobs:
  build-node10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci

  master-check:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lerna:nightly

  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn run lerna:publish

workflows:
  version: 2
  commit:
    jobs:
      - build-node10
      - deploy:
          context: ui5-typescript
          filters:
            tags:
              # Trigger tag publish builds only for packages that actually get published (are public).
              only: /.*(dts-generator|ts-types).*/
            branches:
              ignore: /.*/
# Nightly build currently disabled as we are no longer tracking OpenUI5 master branch
# But rather 1.60.x versions only.
#  nightly:
#    triggers:
#      - schedule:
#          # This is UTC time
#          # https://crontab.guru/#30_9_*_*_*
#          cron: "30 9 * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - master-check
